#Import all the screens
from .Screens import Screen
from .Popup import Popup
from .ClassicScreen import ClassicScreen
from .PlayScreen import PlayScreen
from .GameoverScreen import GameoverScreen
from .HighscoreScreen import HighscoreScreen
from .InstructionsMenuScreen import InstructionsMenuScreen
from .InstructionsScreen import InstructionScreen
from .LocalPVPScreen import LocalPVPScreen
from .MenuScreen import MenuScreen
from .NewhighscoreScreen import NewhighscoreScreen
from .PauseScreen import PauseScreen
from .PlayModesScreen import PlayModeScreen
from .TwoPlayerGameover import TwoPlayerGameoverScreen
from .PVPInstructionsScreen import PVPInstructionsScreen
from .TwoPlayerPauseScreen import TwoPlayerPauseScreen
from .TwoPlayerScreen import TwoPlayerScreen
from .SettingsScreen import SettingsScreen
from .CoopScreen import CoopScreen
from .AIPVPScreen import AIPVPScreen
from .OnlinePVPScreen import OnlinePVPScreen
from .StoryModeScreen import StoryModeScreen
from .OnePlayerModesScreen import OnePlayerModeScreen
from .TutorialScreen import TutorialScreen
from .VictoryScreen import VictoryScreen
from .AICoopScreen import AICoopScreen
from .StoryTemplate import StoryTemplate
from .Stage1Screen import Stage1Screen
from .Stage2Screen import Stage2Screen
from .Stage3Screen import Stage3Screen