#Import all the screens
from .Screens import Screen
from .Popup import Popup
from .PlayScreen import PlayScreen
from .ClassicScreen import ClassicScreen
from .GameoverScreen import GameoverScreen
from .HighscoreScreen import HighscoreScreen
from .InstructionsMenuScreen import InstructionsMenuScreen
from .InstructionsScreen import InstructionScreen
from .LocalPVPScreen import LocalPVPScreen
from .MenuScreen import MenuScreen
from .NewhighscoreScreen import NewhighscoreScreen
from .PauseScreen import PauseScreen
from .PlayModesScreen import PlayModeScreen
from .TwoPlayerGameover import TwoPlayerGameoverScreen
from .PVPInstructionsScreen import PVPInstructionsScreen
from .TwoPlayerPauseScreen import TwoPlayerPauseScreen
from .TwoPlayerScreen import TwoPlayerScreen
from .SettingsScreen import SettingsScreen
from .CoopScreen import CoopScreen
from .AIPVPScreen import AIPVPScreen
from .OnlinePVPScreen import OnlinePVPScreen
